# Generated by Django 2.0 on 2017-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabstudio', '0007_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=False, upload_to='profile/'),
        ),
    ]
