# Generated by Django 2.0 on 2017-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabstudio', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='collabstudio.Tags'),
        ),
    ]
