# Generated by Django 2.0 on 2017-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabstudio', '0009_auto_20171214_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
