# Generated by Django 2.0 on 2017-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabstudio', '0010_auto_20171214_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='caption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
